title: Manga Reader
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple site to read manga online.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Yasinwasnothere.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Yasinwasnothere

# Build settings
theme: minima
